# Generated by Django 2.2.4 on 2020-04-03 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('location', models.FileField(editable=False, null=True, upload_to='emails/')),
                ('email_from', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('body', models.TextField(blank=True)),
                ('body_type', models.CharField(choices=[('h', 'HTML'), ('T', 'Text')], default='T', max_length=1)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('location', models.FileField(upload_to='email/attachments/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.EmailCollection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
