# Generated by Django 2.2.4 on 2020-04-03 10:01

import collector.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.FileField(null=True, upload_to=collector.models.EmailCollection.get_upload_location)),
                ('email_from', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('body', models.TextField(blank=True)),
                ('body_type', models.CharField(choices=[('h', 'HTML'), ('T', 'Text')], default='T', max_length=1)),
                ('is_published', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.FileField(upload_to='email/attachments/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.EmailCollection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
