# Generated by Django 2.2.4 on 2020-04-03 09:40

import collector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcollection',
            name='is_published',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='emailcollection',
            name='location',
            field=models.FileField(editable=False, null=True, upload_to=collector.models.EmailCollection.get_upload_location),
        ),
    ]
