# Generated by Django 2.2.4 on 2020-04-03 10:24

import collector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='location',
            field=models.FileField(upload_to=collector.models.EmailAttachment.get_upload_location),
        ),
        migrations.AlterField(
            model_name='emailcollection',
            name='location',
            field=models.FileField(blank=True, null=True, upload_to=collector.models.EmailCollection.get_upload_location),
        ),
    ]
