# Generated by Django 2.2.4 on 2020-04-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20200403_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcollection',
            name='body',
        ),
        migrations.RemoveField(
            model_name='emailcollection',
            name='body_type',
        ),
    ]
