# Generated by Django 2.2.4 on 2020-04-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_remove_subject_match_type'),
        ('collector', '0003_auto_20200407_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcollection',
            name='parser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.ParsingTask'),
        ),
        migrations.AddField(
            model_name='emailcollection',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.Template'),
        ),
    ]
