# Generated by Django 2.2.4 on 2020-04-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20200407_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcollection',
            name='is_published',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
