# Generated by Django 2.2.4 on 2020-04-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20200407_0605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcollection',
            options={'ordering': ('-created_at',), 'verbose_name': 'email', 'verbose_name_plural': 'emails'},
        ),
    ]
