# Generated by Django 2.2.4 on 2020-04-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_auto_20200413_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcollection',
            name='parser',
        ),
    ]
