# Generated by Django 2.2.4 on 2020-04-15 11:52

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_remove_emailcollection_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcollection',
            name='meta',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
