# Generated by Django 2.2.4 on 2020-04-15 11:59

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_emailcollection_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcollection',
            name='template_match_status',
            field=models.CharField(choices=[('NEW', 'New'), ('MULTIPLE_MATCH', 'Multiple Template Match'), ('NOT_MATCH', 'No Template Match')], default='NEW', max_length=15),
        ),
        migrations.AlterField(
            model_name='emailcollection',
            name='meta',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='Meta Fields'),
        ),
    ]
