# Generated by Django 2.2.4 on 2020-04-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20200415_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcollection',
            name='template_match_status',
            field=models.CharField(choices=[('NEW', 'New'), ('MULTIPLE_MATCH', 'Multiple template match found'), ('NOT_MATCH', 'No template match found'), ('MATCH_FOUND', 'Template matched')], default='NEW', max_length=15),
        ),
    ]
