# Generated by Django 2.2.4 on 2020-04-16 14:12

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_auto_20200415_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcollection',
            name='meta',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}, null=True, verbose_name='Extracted data'),
        ),
    ]
