# Generated by Django 2.2.4 on 2020-05-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_sbemailparsing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbemailparsing',
            options={'verbose_name': 'service bus email parsing'},
        ),
        migrations.RenameField(
            model_name='sbemailparsing',
            old_name='BodyHtmlContent',
            new_name='body_html_content',
        ),
        migrations.RenameField(
            model_name='sbemailparsing',
            old_name='BodyPlainText',
            new_name='body_plaintext',
        ),
        migrations.RenameField(
            model_name='sbemailparsing',
            old_name='ClientId',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='sbemailparsing',
            old_name='FromAddress',
            new_name='from_address',
        ),
        migrations.RenameField(
            model_name='sbemailparsing',
            old_name='InboxUsername',
            new_name='inbox_username',
        ),
        migrations.RenameField(
            model_name='sbemailparsing',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='sbemailparsing',
            old_name='ToAddresses',
            new_name='to_addresses',
        ),
        migrations.RenameField(
            model_name='sbemailparsing',
            old_name='UniqueIdentifier',
            new_name='unique_identifier',
        ),
    ]
