# Generated by Django 2.2.4 on 2020-05-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_auto_20200512_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcollection',
            name='email_to',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
