# Generated by Django 2.2.4 on 2020-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0018_auto_20200521_0846'),
        ('collector', '0018_emailcollection_email_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcollection',
            name='match_templates',
            field=models.ManyToManyField(related_name='match_templates', to='parsers.Template'),
        ),
    ]
