# Generated by Django 2.2.4 on 2020-06-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0019_pdfparsingtask_pdftemplate'),
        ('collector', '0020_auto_20200602_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcollection',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.PDFTemplate'),
        ),
    ]
