# Generated by Django 2.2.4 on 2020-06-04 13:14

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0019_pdfparsingtask_pdftemplate'),
        ('collector', '0021_pdfcollection_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserExecutionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('extracted_data', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.EmailCollection')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.Template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
