# Generated by Django 2.2.4 on 2020-06-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_parserexecutionhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parserexecutionhistory',
            options={'verbose_name': 'parser execution history', 'verbose_name_plural': 'parser execution histories'},
        ),
        migrations.AddField(
            model_name='parserexecutionhistory',
            name='is_published',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='emailcollection',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.Template', verbose_name='latest parser executed'),
        ),
    ]
