# Generated by Django 2.2.4 on 2020-06-21 10:57

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0019_pdfparsingtask_pdftemplate'),
        ('collector', '0023_auto_20200604_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcollection',
            name='match_templates',
            field=models.ManyToManyField(blank=True, related_name='match_templates', to='parsers.PDFTemplate', verbose_name='templates'),
        ),
        migrations.AlterField(
            model_name='pdfcollection',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.PDFTemplate', verbose_name='latest pdf parser executed'),
        ),
        migrations.CreateModel(
            name='PDFParserExecutionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('extracted_data', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('is_published', models.BooleanField(default=False, editable=False)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.PDFCollection')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.PDFTemplate')),
            ],
            options={
                'verbose_name': 'pdf parser execution history',
                'verbose_name_plural': 'pdf parser execution histories',
            },
        ),
    ]
