# Generated by Django 2.2.4 on 2020-04-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('parser', models.CharField(choices=[('stubhub_subject_parser', 'Stubhub cancel order')], max_length=75)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='template',
            name='parser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.ParsingTask'),
        ),
    ]
