# Generated by Django 2.2.4 on 2020-04-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_auto_20200403_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='match_type',
        ),
    ]
