# Generated by Django 2.2.4 on 2020-04-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_remove_subject_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='domain',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='template',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='subject',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='parsers.Template'),
        ),
    ]
