# Generated by Django 2.2.4 on 2020-04-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_auto_20200407_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='from_email',
            new_name='email_from',
        ),
    ]
