# Generated by Django 2.2.4 on 2020-04-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_auto_20200407_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='to_email',
            new_name='email_to',
        ),
    ]
