# Generated by Django 2.2.4 on 2020-04-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_auto_20200407_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingtask',
            name='parser',
            field=models.CharField(choices=[('subject', 'Subject Parser'), ('email_body', 'Email Body Parser'), ('attachment_parser', 'Attachment  Parser')], max_length=75),
        ),
    ]
