# Generated by Django 2.2.4 on 2020-04-07 10:01

from django.db import migrations
import django_regex.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0007_auto_20200407_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingtask',
            name='regex',
            field=django_regex.fields.RegexField(max_length=128, null=True),
        ),
    ]
