# Generated by Django 2.2.4 on 2020-04-07 10:24

from django.db import migrations
import django_regex.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0008_parsingtask_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='subject',
            field=django_regex.fields.RegexField(blank=True, max_length=128, null=True),
        ),
    ]
