# Generated by Django 2.2.4 on 2020-04-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0009_template_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingtask',
            name='title',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
