# Generated by Django 2.2.4 on 2020-04-13 12:24

from django.db import migrations, models
import django_regex.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0010_parsingtask_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsingtask',
            options={'verbose_name': 'parser', 'verbose_name_plural': 'parsers'},
        ),
        migrations.AlterField(
            model_name='parsingtask',
            name='parser',
            field=models.CharField(choices=[('subject', 'Subject Parser'), ('body', 'Email Body Parser'), ('parser', 'Attachment  Parser')], max_length=75, verbose_name='Parser Type'),
        ),
        migrations.AlterField(
            model_name='parsingtask',
            name='regex',
            field=django_regex.fields.RegexField(help_text='regular expression field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=django_regex.fields.RegexField(blank=True, help_text='regular expression field', max_length=128, null=True),
        ),
    ]
