# Generated by Django 2.2.4 on 2020-04-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0011_auto_20200413_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='parser',
        ),
        migrations.AddField(
            model_name='parsingtask',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.Template'),
        ),
    ]
