# Generated by Django 2.2.4 on 2020-04-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0014_auto_20200415_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsingtask',
            old_name='parser',
            new_name='parser_type',
        ),
    ]
