# Generated by Django 2.2.4 on 2020-04-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_auto_20200420_0429'),
        ('parsers', '0015_auto_20200415_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='desination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='destination.DestinationQueue'),
        ),
    ]
