# Generated by Django 2.2.4 on 2020-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0016_template_desination'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_for',
            field=models.CharField(choices=[('E', 'Email Parsing'), ('Q', 'Queue Parsing'), ('B', 'Both Email andQueue Parsing')], default='B', max_length=10),
        ),
    ]
