# Generated by Django 2.2.4 on 2020-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0017_template_template_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_for',
            field=models.CharField(choices=[('E', 'Email Parsing'), ('Q', 'Queue Parsing'), ('B', 'Both Email and Queue Parsing')], default='B', max_length=10),
        ),
    ]
