# Generated by Django 2.2.4 on 2020-06-02 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_regex.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destination', '0002_auto_20200420_0429'),
        ('parsers', '0018_auto_20200521_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('title', models.CharField(max_length=75)),
                ('email_from', models.EmailField(blank=True, max_length=254)),
                ('email_to', models.EmailField(blank=True, max_length=254)),
                ('pdf_type', models.IntegerField(null=True)),
                ('desination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='destination.DestinationQueue')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFParsingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('title', models.CharField(max_length=35, null=True)),
                ('var_name', models.CharField(max_length=36, null=True, verbose_name='variable name')),
                ('regex', django_regex.fields.RegexField(help_text='regular expression field', max_length=128, null=True)),
                ('desc', models.TextField(blank=True, editable=False)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfparsers', to='parsers.PDFTemplate')),
            ],
            options={
                'verbose_name': 'pdfparser',
                'verbose_name_plural': 'pdfparsers',
            },
        ),
    ]
