# Generated by Django 2.2.4 on 2020-04-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('queue', models.CharField(max_length=75, verbose_name='queue name')),
                ('desc', models.TextField(editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('queue', 'is_active')},
            },
        ),
    ]
