# Generated by Django 2.2.4 on 2020-04-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationqueue',
            options={'verbose_name': 'queue', 'verbose_name_plural': 'queues'},
        ),
    ]
